name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.7
homepage: https://github.com/lejard-h/google_maps_webservice
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  http: ">=0.11.0 <1.0.0"
  meta: ^1.1.0

dev_dependencies:
  test: ^1.3.0
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
